apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-service
  namespace: default
  labels:
    app: items-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items-service
  template:
    metadata:
      labels:
        app: items-service
    spec:
      containers:
      - name: items-service
        image: ghcr.io/nextinterfaces/items-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: COMMIT_SHA
          value: "unknown"
        # PostgreSQL connection
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        # OpenTelemetry configuration
        - name: OTEL_ENABLED
          value: "true"  # Enabled for production with Jaeger
        - name: OTEL_SERVICE_NAME
          value: "items-service"
        - name: OTEL_SERVICE_VERSION
          value: "1.0.0"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://jaeger:4318"  # Jaeger service in the cluster
        - name: OTEL_LOG_LEVEL
          value: "info"  # Options: info, debug, verbose
        # OpenSearch logging configuration
        - name: OPENSEARCH_ENABLED
          value: "true"  # Enable sending logs to OpenSearch
        - name: OPENSEARCH_NODE
          value: "http://opensearch:9200"  # OpenSearch service in the cluster
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /v1/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /v1/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: items-service
  namespace: default
  labels:
    app: items-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: items-service

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: items-service
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - app.roussev.com
    secretName: items-service-tls
  rules:
  - host: app.roussev.com
    http:
      paths:
      - path: /items(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: items-service
            port:
              number: 80
