# This file is a template. Do not apply directly.
# Use 'task postgres:create-secret' to create the secret from your .env file.
#
# The secret will be created with the following structure:
# apiVersion: v1
# kind: Secret
# metadata:
#   name: postgres-secret
#   namespace: default
# type: Opaque
# stringData:
#   POSTGRES_USER: <from .env>
#   POSTGRES_PASSWORD: <from .env>
#   POSTGRES_DB: <from .env>

