apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hetzner-volume
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: hetzner-volume

